version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"  # Expose MongoDB port
    networks:
      - my-network
    volumes:
      - mongo-data:/data/db  # Persist MongoDB data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "5000:5000"  # Expose backend port
    environment:
      MONGO_URI: mongodb://mongo:27017/mydatabase  # MongoDB connection URI
      MONGO_CONNECTION_STRING: ${MONGO_CONNECTION_STRING}
      PORT: ${PORT}
      SESSION_SECRET: ${SESSION_SECRET}
    volumes:
      - ./backend:/usr/src/app
      # - ./backend/node_modules:/app/node_modules
    depends_on:
      - mongo  # Ensure MongoDB starts before the backend
    networks:
      - my-network

  frontend:
    build:
      context: ./frontend/exam_project_work
      dockerfile: Dockerfile
    container_name: frontend

    volumes:
      - ./frontend/exam_project_work:/usr/src/app:rw
      - node_modules:/usr/src/app/node_modules
    # working_dir: ./src
    ports:
      - "4200:4200"
    networks:
      - my-network

networks:
  my-network:
    driver: bridge

volumes:
  mongo-data:
    driver: local
  node_modules: