# Stage 1: Build the Angular application
FROM node:20 AS build

# Set the working directory in the container
WORKDIR /usr/src/app

# Copy package.json and package-lock.json (or yarn.lock) to the working directory
COPY package*.json ./

# Install the dependencies
RUN npm install

# Copy the rest of your application code to the container
COPY . .

# Build the Angular application for production
RUN npm run build --prod

RUN ng serve

# Stage 2: Serve the application with Nginx
FROM nginx:alpine

# Copy the Angular build artifacts from the build stage to the Nginx HTML directory
COPY --from=build /usr/src/app/dist/exam_project_work /usr/share/nginx/html

# Expose port 80 to allow traffic to the container
EXPOSE 80

# Start Nginx and keep it running in the foreground
CMD ["nginx", "-g", "daemon off;"]
